FROM debian:13.1-slim AS build-gmp

WORKDIR /srv/gmp-4.3.2

RUN --mount=type=cache,target=/var/cache/apt,id=cache-apt-gmp \
    --mount=type=cache,target=/var/lib/apt,id=cache-apt-gmp \
    DEBIAN_FRONTEND=noninteractive apt update \
    && apt install wget vim xz-utils gcc-12 m4 make -y

RUN --mount=type=cache,target=/var/download,id=cache-download-gmp \
    [ -f /var/download/gmp.tar.gz ] || wget --no-verbose https://ftpmirror.gnu.org/gmp/gmp-4.3.2.tar.gz \
    -O /var/download/gmp.tar.gz \
    && tar -xf /var/download/gmp.tar.gz -C /srv/

RUN CC=gcc-12 \
    ./configure \
    --build=$(uname -m)-unknown-linux-gnu \
    --prefix /opt/gmp-4.3.2
RUN make -j$(nproc)
RUN make install

FROM debian:13.1-slim AS build-mpfr

WORKDIR /srv/mpfr-2.4.2

RUN --mount=type=cache,target=/var/cache/apt,id=cache-apt-mpfr \
    --mount=type=cache,target=/var/lib/apt,id=cache-apt-mpfr \
    DEBIAN_FRONTEND=noninteractive apt update \
    && apt install wget vim xz-utils gcc make -y

RUN --mount=type=cache,target=/var/download,id=cache-download-mpfr \
    [ -f /var/download/mpfr.tar.gz ] || wget --no-verbose https://ftpmirror.gnu.org/mpfr/mpfr-2.4.2.tar.gz \
    -O /var/download/mpfr.tar.gz \
    && tar -xf /var/download/mpfr.tar.gz -C /srv/

COPY --link --from=build-gmp /opt /opt

RUN ./configure \
    --build=$(uname -m)-unknown-linux-gnu \
    --prefix /opt/mpfr-2.4.2 \
    --with-gmp=/opt/gmp-4.3.2
RUN make -j$(nproc)
RUN make install


FROM debian:13.1-slim AS build-mpc

WORKDIR /srv/mpc-1.0.1

RUN --mount=type=cache,target=/var/cache/apt,id=cache-apt-mpc \
    --mount=type=cache,target=/var/lib/apt,id=cache-apt-mpc \
    DEBIAN_FRONTEND=noninteractive apt update \
    && apt install wget vim xz-utils gcc make -y

RUN --mount=type=cache,target=/var/download,id=cache-download-mpc \
    [ -f /var/download/mpc.tar.gz ] || wget --no-verbose https://ftpmirror.gnu.org/mpc/mpc-1.0.1.tar.gz \
    -O /var/download/mpc.tar.gz \
    && tar -xf /var/download/mpc.tar.gz -C /srv/

COPY --link --from=build-mpfr /opt /opt

RUN ./configure \
    --prefix /opt/mpc-1.0.1 \
    --with-gmp=/opt/gmp-4.3.2 \
    --with-mpfr=/opt/mpfr-2.4.2
RUN make -j$(nproc)
RUN make install


FROM debian:13.1-slim AS build-gcc

WORKDIR /srv/gcc-8.2.0

RUN --mount=type=cache,target=/var/cache/apt,id=cache-apt-gcc \
    --mount=type=cache,target=/var/lib/apt,id=cache-apt-gcc \
    DEBIAN_FRONTEND=noninteractive apt update \
    && apt install wget vim xz-utils build-essential -y

RUN --mount=type=cache,target=/var/download,id=cache-download-gcc \
    wget --no-verbose https://gnu.c3sl.ufpr.br/ftp/gcc/gcc-8.2.0/gcc-8.2.0.tar.gz \
    -O /var/download/gcc-8.2.0.tar.gz \
    && tar -xf /var/download/gcc-8.2.0.tar.gz -C /srv/

COPY --link --from=build-mpc /opt /opt

RUN ln -s /opt/mpfr-2.4.2/lib/libmpfr.so.1 /lib/$(uname -m)-linux-gnu/libmpfr.so.1 && \
    ln -s /opt/gmp-4.3.2/lib/libgmp.so.3 /lib/$(uname -m)-linux-gnu/libgmp.so.3 && \
    ldconfig

# GMP 4.2+, MPFR 2.4.0+ and MPC 0.8.0+.
RUN ./configure \
    --prefix /opt/gcc-8.2.0 \
    --with-gmp=/opt/gmp-4.3.2 \
    --with-mpfr=/opt/mpfr-2.4.2 \
    --with-mpc=/opt/mpc-1.0.1 \
    --enable-languages=c,c++ \
    --disable-multilib \
    --disable-libcc1 \
    --disable-libitm \
    --disable-libsanitizer \
    --disable-libquadmath \
    --disable-libvtv

RUN make -j$(nproc)
RUN make install

FROM debian:13.1-slim AS release

RUN --mount=type=cache,target=/var/cache/apt,id=cache-apt-gcc \
    --mount=type=cache,target=/var/lib/apt,id=cache-apt-gcc \
    DEBIAN_FRONTEND=noninteractive apt update \
    && apt install build-essential -y

COPY --link --from=build-gcc /opt /opt

RUN echo "/opt/gmp-4.3.2/lib" > /etc/ld.so.conf.d/gmp.conf && \
    echo "/opt/mpfr-2.4.2/lib" > /etc/ld.so.conf.d/mpfr.conf && \
    echo "/opt/mpc-1.0.1/lib" > /etc/ld.so.conf.d/mpc.conf && \
    ldconfig

RUN ldconfig -n /opt/gcc-8.2.0/lib/../lib64 && \
    ln -sf /opt/gcc-8.2.0/bin/gcc /usr/bin/gcc
