FROM debian:13.1-slim AS build-httpd

WORKDIR /srv/httpd-2.2.3

RUN --mount=type=cache,target=/var/cache/apt,id=cache-apt \
    --mount=type=cache,target=/var/lib/apt,id=cache-apt \
    DEBIAN_FRONTEND=noninteractive apt update  \
    && apt install wget gcc-12 make -y

RUN --mount=type=cache,target=/var/download,id=cache-download \
    [ -f /var/download/httpd.tar.gz ] || wget --no-verbose https://archive.apache.org/dist/httpd/httpd-2.2.3.tar.gz \
    -O /var/download/httpd.tar.gz \
    && tar -xf /var/download/httpd.tar.gz -C /srv/

RUN CC=gcc-12 \
    ./configure \
    --build=$(uname -m)-unknown-linux-gnu \
    --enable-so \
    --enable-rewrite \
    --prefix /opt/httpd-2.2.3
RUN make -j$(nproc)
RUN make install

RUN echo 'Include conf.d/*.conf' >> /opt/httpd-2.2.3/conf/httpd.conf
COPY httpd.conf.d /opt/httpd-2.2.3/conf.d/

FROM scratch AS release

COPY --from=build-httpd /opt/httpd-2.2.3 /opt/httpd-2.2.3
