FROM debian:13.1-slim AS build-curl

WORKDIR /srv/curl-7.19.7

RUN --mount=type=cache,target=/var/cache/apt,id=cache-apt-curl \
    --mount=type=cache,target=/var/lib/apt,id=cache-apt-curl \
    DEBIAN_FRONTEND=noninteractive apt update  \
    && apt install wget gcc-12 make -y

RUN --mount=type=cache,target=/var/download,id=cache-download-curl \
    [ -f /var/download/curl.tar.gz ] || wget --no-verbose https://curl.se/download/archeology/curl-7.19.7.tar.gz \
    -O /var/download/curl.tar.gz \
    && tar -xf /var/download/curl.tar.gz -C /srv/

COPY --link --from=ghcr.io/clagomess/docker-php-5.2:openssl /opt/openssl-0.9.8h /opt/openssl-0.9.8h

RUN CC=gcc-12 \
    ./configure \
    --build=$(uname -m)-unknown-linux-gnu \
    --prefix=/opt/curl-7.19.7 \
    --with-ssl=/opt/openssl-0.9.8h \
    --disable-shared
RUN make -j$(nproc)
RUN make install

FROM scratch AS release

COPY --from=build-curl /opt/curl-7.19.7 /opt/curl-7.19.7
